# This file is used to allow developer access to the database and
# the usage of GUI database tools. Do not use in production systems

services:
  odoo:
    environment:
      BOOTSTRAP_DEBUGGER: "${BOOTSTRAP_DEBUGGER:-}"
    ports:
      - 127.0.0.1:${DEBUGPY_PORT:-5678}:5678
  db:
    networks:
      default:
      public:
    ports:
      - "127.0.0.1:${DATABASE_PORT:-6543}:5432"
