version: "3.5"

services:
  # Odoo
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.10"
        UID: "${UID:-1000}"
        GID: "${UID:-1000}"
      target: base
    depends_on:
      - db
    env_file:
      - .env
    environment:
      UID: "${UID:-1000}"
      GID: "${GID:-1000}"
      UMASK: "${UMASK:-002}"
      ODOO_DB_HOST: &dbhost ${DB_HOST:-db}
      ODOO_DB_NAME: &dbname ${DB_NAME:-odoo}
      ODOO_DB_PASSWORD: &dbpass $DB_PASSWORD
      ODOO_DB_PORT: &dbport ${DB_PORT:-5432}
      ODOO_DB_USER: &dbuser ${DB_USER:-odoo}
      PGDATABASE: *dbname
      PGHOST: *dbhost
      PGPASSWORD: *dbpass
      PGPORT: *dbport
      PGUSER: *dbuser
    image: dob:${DOB_TAG:-latest}
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_SIZE:-1g}"
        max-file: "${LOG_COUNT:-5}"
    networks:
      default:
      public:
    ports:
      - ${HTTP_PORT:-127.0.0.1:8069}:8069
      - ${HTTP_LONGPOLLING_PORT:-127.0.0.1:8072}:8072
    tty: true
    user: odoo
    volumes:
      - ./filestore:/srv/odoo/filestore:rw,z
      - ./odoo:/srv/odoo/odoo
      - ./ssh:/srv/odoo/.ssh
    healthcheck:
      test: ["CMD", "curl", "-sfo", "/dev/null", "http://127.0.0.1:8069"]
      interval: 15s
      timeout: 1s
      retries: 3

  # Database
  db:
    image: postgres:${DB_VERSION:-latest}
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_USER: *dbuser
      POSTGRES_PASSWORD: *dbpass
    command: --work_mem=32MB
    shm_size: 512mb
    tty: true
    volumes:
      - db:/var/lib/postgresql/data:z
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *dbuser, "-d", *dbname]
      interval: 5s
      timeout: 1s
      retries: 3

networks:
  default:
    internal: True
  public:

volumes:
  db:
