# This file is used to setup a mailhog as sink for all mails generated
# by odoo. This is meant to be used on test or development machines

services:
  # Odoo
  odoo:
    depends_on:
      - mailhog
    environment:
      ODOO_SMTP_SERVER: mailhog
      ODOO_SMTP_PORT: 1025

  mailhog:
    image: mailhog/mailhog:latest
    networks:
      default:
      public:
    ports:
      - ${MAILHOG_PORT:-127.0.0.1:8025}:8025
    tty: true

networks:
  default:
    internal: True
  public:
