# Defaults for all prettier-supported languages.
# Prettier will complete this with settings from .editorconfig file.
bracketSpacing: false
endOfLine: lf
htmlWhitespaceSensitivity: "strict"
printWidth: 88
proseWrap: always
semi: true
tabWidth: 4
trailingComma: "es5"
